version: 2

sources:
  - name: databricks_sample_data
    description: 'A sample database provided by Databricks.'
    database: samples
    schema: tpcds_sf1000
    tables:
      - name: store_sales
        description: 'Details about the sales in the store.'